const ranksByGame = {
    Valorant: {
        ranks: [
            "Unranked",
            "Iron",
            "Bronze",
            "Silver",
            "Gold",
            "Platinum",
            "Diamond",
            "Ascendant",
            "Immortal",
            "Radiant",
        ],
        subranks: {
            Unranked: 1,
            Radiant: 1,
            default: 3,
        },
        capacity: 5,
    },
    LoL: {
        ranks: [
            "Unranked",
            "Iron",
            "Bronze",
            "Silver",
            "Gold",
            "Platinum",
            "Emerald",
            "Diamond",
            "Master",
            "Grandmaster",
            "Challenger",
        ],
        subranks: {
            Unranked: 1,
            default: 4,
            Master: 1,
            Grandmaster: 1,
            Challenger: 1,
        },
        capacity: 5,
    },
    Overwatch: {
        ranks: [
            "Unranked",
            "Bronze",
            "Silver",
            "Gold",
            "Platinum",
            "Diamond",
            "Master",
            "Grandmaster",
            "Champion",
            "Top 500",
        ],
        subranks: {
            default: 5,
            Unranked: 1,
            Master: 3,
            Grandmaster: 1,
            Champion: 1,
            "Top 500": 1,
        },
        capacity: 5,
    },
    Fortnite: {
        ranks: [
            "Unranked",
            "Bronze",
            "Silver",
            "Gold",
            "Platinum",
            "Diamond",
            "Elite",
            "Champion",
            "Unreal",
        ],
        subranks: {
            default: 3,
            Unranked: 1,
            Elite: 1,
            Champion: 1,
            Unreal: 1,
        },
        capacity: 4,
    },
};

export default ranksByGame;
